name: PR Title Checker

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  title-format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR Title Format
        uses: actions/github-script@v6
        with:
          script: |
            const title = context.payload.pull_request.title;
            
            // Validate type prefix (either (type) or type: or BREAKING:)
            const typePattern = /^(?:\((docs|test|chore|fix|feat|refactor)\)|(docs|test|chore|fix|feat|refactor):?|(BREAKING):\s+/i;
            const hasValidType = typePattern.test(title);
            
            if (!hasValidType) {
              core.setFailed(`PR title must start with:
              - (type) (e.g., "(feat)")
              - type: (e.g., "feat:")
              - type (e.g., "feat ")
              - BREAKING:
              Where type is one of: docs, test, chore, fix, feat, refactor`);
            }
            
            // Validate O3 ticket format if present
            const ticketPattern = /(O3|o3|03)-\d+/;
            const hasTicketReference = ticketPattern.test(title);
            
            if (hasTicketReference) {
              if (/o3-\d+/.test(title)) {
                core.setFailed('Ticket reference must use uppercase O (O3) not lowercase (o3)');
              } else if (/03-\d+/.test(title)) {
                core.setFailed('Ticket reference must use uppercase O (O3) not zero (03)');
              } else if (!/O3-\d+:/.test(title)) {
                core.setFailed('Ticket reference must be followed by colon (O3-XXXX:)');
              }
            }
            
            // Validate overall structure
            const validPattern = /^(?:\((docs|test|chore|fix|feat|refactor)\)|(docs|test|chore|fix|feat|refactor):?|(BREAKING):)\s+(?:(O3-\d+):\s+)?[^ ].*$/;
            if (!validPattern.test(title)) {
              core.setFailed(`Invalid PR title structure. Valid examples:
              - (feat) O3-1234: Implement new feature
              - fix: O3-4567: Resolve issue
              - chore Update dependencies
              - BREAKING: O3-7890: Major change
              - (test) Add unit tests`);
            }