name: PR Title Checker

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  validate-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Title Format
        uses: actions/github-script@v6
        with:
          script: |
            const title = context.payload.pull_request.title.trim();
            
            // Define valid patterns
            const validPatterns = [
              // Pattern 1: (type) O3-XXXX: Description
              /^\((docs|test|chore|fix|feat|refactor)\)\s+(O3-\d+):\s+.+$/,
              // Pattern 2: (type) Description (no ticket)
              /^\((docs|test|chore|fix|feat|refactor)\)\s+[^ ].+$/,
              // Pattern 3: BREAKING: O3-XXXX: Description
              /^BREAKING:\s+(O3-\d+):\s+.+$/,
              // Pattern 4: BREAKING: Description (no ticket)
              /^BREAKING:\s+[^ ].+$/
            ];

            // Check if title matches any valid pattern
            const isValid = validPatterns.some(pattern => pattern.test(title));
            
            if (!isValid) {
              core.setFailed(`Invalid PR title format. Must follow one of these patterns:
              
              With ticket reference:
              - "(feat) O3-1234: Description"
              - "BREAKING: O3-1234: Description"
              
              Without ticket reference:
              - "(feat) Description"
              - "BREAKING: Description"
              
              Strict Requirements:
              1. Types must be in parentheses: (docs), (test), (chore), (fix), (feat), (refactor)
              2. Only "BREAKING" (uppercase) is allowed without parentheses but must include a colon
              3. Ticket reference (if present) must be "O3-XXXX" (uppercase O, not zero)
              4. Ticket reference must be followed by a colon
              5. No colon after parenthesized type (only after ticket reference)
              6. Must include a description after the prefix`);
            }

            // Additional strict checks
            // 1. Check for lowercase types without parentheses
            if (/^(docs|test|chore|fix|feat|refactor)[^\(]/.test(title)) {
              core.setFailed('Type prefix must be in parentheses (e.g., "(feat)")');
            }
            
            // 2. Check for BREAKING case
            if (/^breaking:/i.test(title) && !/^BREAKING:/.test(title)) {
              core.setFailed('"BREAKING" must be uppercase and followed by colon');
            }
            
            // 3. Check ticket format if present
            const ticketMatch = title.match(/(o3|03|O3)-\d+/);
            if (ticketMatch) {
              const ticketRef = ticketMatch[0];
              if (ticketRef.startsWith('o3')) {
                core.setFailed('Ticket reference must use uppercase O (O3) not lowercase (o3)');
              } else if (ticketRef.startsWith('03')) {
                core.setFailed('Ticket reference must use uppercase O (O3) not zero (03)');
              } else if (!/:/.test(title.split(ticketRef)[1])) {
                core.setFailed('Ticket reference must be followed by a colon (O3-1234:)');
              }
            }
            
            // 4. Check for colons in wrong places
            if (/^\([^)]+\):/.test(title)) {
              core.setFailed('No colon should appear immediately after parenthesized type');
            }