name: PR Title Checker

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  check-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Title Format
        uses: amannn/action-semantic-pull-request@v5
        with:
          types: |
            docs
            test
            chore
            fix
            feat
            refactor
            BREAKING
          requireScope: false
          headerPattern: |
            ^(?:
              # Either: (type) [O3-ticket]: subject
              \((?<type>BREAKING|docs|test|chore|fix|feat|refactor)\)\s(?:(?<ticket>O3-[0-9]+):\s)?(?<subject>.+)$
              |
              # Or: BREAKING: subject (no parentheses, no ticket)
              (?<type>BREAKING):\s(?<subject>.+)$
            )
          headerPatternCorrespondence: type,ticket,subject
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}