name: PR Title Checker

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  check-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Title Format
        uses: amannn/action-semantic-pull-request@v5
        with:
          types: |
            docs
            test
            chore
            fix
            feat
            BREAKING
          requireScope: false
          headerPattern: "^(?:(?:(feat|fix|chore|docs|test|refactor|BREAKING):? ?(?:O3-[0-9]+: )?)|\\((feat|fix|chore|docs|test|refactor)\\)) (?:(O3-[0-9]+: )?)?.+$"
          headerPatternCorrespondence: type,ticket,subject
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
