name: PR Title Checker

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  check-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Title Format
        uses: amannn/action-semantic-pull-request@v5
        with:
          types: |
            docs
            test
            chore
            fix
            feat
            refactor
            BREAKING
          requireScope: false
          headerPattern: ^(\((?<type1>docs|test|chore|fix|feat|refactor)\)\s(?:(?<ticket1>O3-[0-9]+):\s)?(?<subject1>.+))|^(?<type2>BREAKING):\s(?<subject2>.+)$
          headerPatternCorrespondence: |
            type1,ticket1,subject1
            type2,,subject2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
